# Generated by Django 3.0 on 2021-02-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fees',
            field=models.IntegerField(default=100),
        ),
    ]
